ruby "2.5.1"
source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "docker-api"
gem "dotenv-rails"
gem "pg"
gem "puma"
gem "rails"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  # Call `byebug` to stop execution and get a debugger console
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "capybara"
  gem "launchy"
  gem "pry"
  gem "rspec-rails"
end

group :development do
  gem "listen"
end
